### ISSUE TITLE
Unable to upload screenshot to Klov server

### ISSUE THREAD

**Issue by munnamathew** [extent-framework/klov#36]
Hi ,

I am getting a HttpHostConnectException exception while trying to upload screenshots to Klov server. Please let me know if anyone has a solution to fix this issue? 

Klov version - 0.2.5
Code snippet : 

Initializing connection : 

		
		//This should be coming from the config JSON file. Hard coding for the time being
                ExtentHtmlReporter htmlreport = new ExtentHtmlReporter(FilePath);
		htmlreport.config().setDocumentTitle(projectName + "_" + scenarioName);
		reporter = new ExtentReports();
		reporter.setSystemInfo("OS : ", "Windows 10");
		reporter.setSystemInfo("Java Version : ","1.8.0_211");
		reporter.setSystemInfo("Browser : ","Chrome");
		reporter.attachReporter(htmlreport);
		reporter.setReportUsesManualConfiguration(true);

		try{
			//intialize with a project name, build name
			ExtentKlovReporter klov = new ExtentKlovReporter(projectName, scenarioName + "_" + Date);
			// address, host/port of MongoDB
			klov.initMongoDbConnection("hostname", 27017);
			// Klov server address
			klov.initKlovServerConnection("serveraddress");

			reporter.attachReporter(klov);
		}
		catch(Exception e)
		{
			//If KLOV connection failed continue with html report
			System.out.println("Klov server not running");
		}

Add Screenshot : 
```
MediaEntityModelProvider mediaModel =  MediaEntityBuilder.createScreenCaptureFromPath(screenshot).build();
			logger.log(Status.INFO, screenshotName, mediaModel);

```
Exception thrown : 
	org.apache.http.conn.HttpHostConnectException: Connect to vnname:80 [vm details] failed: Connection timed out: connect at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158 org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(
•	PoolingHttpClientConnectionManager.java:353)    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
•	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
•	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
•	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
•	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
•	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
•	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
•	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
•	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
•	at com.aventstack.extentreports.mediastorage.impl.HttpMediaManagerImplKlov.storeMedia(HttpMediaManagerImplKlov.java:68)
•	at com.aventstack.extentreports.mediastorage.KlovMediaStorageHandler.saveScreenCapture(KlovMediaStorageHandler.java:47)
•	at com.aventstack.extentreports.reporter.ExtentKlovReporter.saveScreenCapture(ExtentKlovReporter.java:683)
•	at com.aventstack.extentreports.reporter.ExtentKlovReporter.onScreenCaptureAdded(ExtentKlovReporter.java:675)
•	at com.aventstack.extentreports.ExtentObservable.addScreenCapture(ExtentObservable.java:367)
•	at com.aventstack.extentreports.ExtentTest.addLog(ExtentTest.java:363)
•	at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:308)
•	at com.aventstack.extentreports.ExtentTest.pass(ExtentTest.java:528)
•	at com.acsf.library.Common.ExtentReport.logScreenshot(ExtentReport.java:280)
•	at com.acsf.utilities.Utility.captureScreenshot(Utility.java:48)
•	at com.acsf.library.Common.Common.captureScreenShot(Common.java:501)
•	at com.acsf.library.FSM.Call.createCallTemplate(Call.java:230)
•	at com.acsf.testcases.FSM.SmokeTests.TC_323397.testcase_323397(TC_323397.java:37)
•	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
•	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
•	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
•	at java.lang.reflect.Method.invoke(Method.java:498)
•	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
•	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
•	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
•	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
•	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
•	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
•	at org.testng.TestRunner.privateRun(TestRunner.java:773)
•	at org.testng.TestRunner.run(TestRunner.java:623)
•	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
•	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
•	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
•	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
•	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
•	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
•	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
•	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
•	at org.testng.TestNG.run(TestNG.java:1018)
•	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
•	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
•	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
•	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
•	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
•	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
	Caused by: java.net.ConnectException: Connection timed out: connect
•	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
•	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
•	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
•	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
•	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
•	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
•	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
•	at java.net.Socket.connect(Socket.java:589)
•	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
•	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)

**Comment by munnamathew** [comment]
The issue is resolved , I am able to upload screenshots now. The problem was klov was using default port(80) to upload the screenshot, now I have specified the port number(8080).
